CREATE TABLE city (
  id UUID NOT NULL,
   name VARCHAR(30) NOT NULL,
   state_id UUID NOT NULL,
   CONSTRAINT pk_city PRIMARY KEY (id)
);

ALTER TABLE city ADD CONSTRAINT FK_CITY_ON_STATE FOREIGN KEY (state_id) REFERENCES state (id);